djsite/account/urls.py
from django.urls import path, re_path
from . import views 
# from django.contrib.auth
# import views as auth_views

app_name = "account"
urlpatterns = [
    path('login/', views.user_login, name='user_login'),
    # path('login/', auth_views.LoginView.as_view(template_name='account/login2.html'), name='user_login'),
    # path('logout/', auth_views.LogoutView.as_view(template_name='account/logout.html'), name='user_logout'),
    # path('register/', views.register, name='user_register'),
    # path('password-change/', auth_views.PasswordChangeView.as_view(template_name="account/password_change_form.html", success_url="/account/password-change-done/"), name='password_change'),
    # path('password-change-done/', auth_views.PasswordChangeDoneView.as_view(template_name="account/password_change_done.html"), name='password_change_done'),
    # path('password-reset/', auth_views.PasswordResetView.as_view(template_name="account/password_reset_form.html", email_template_name="account/password_reset_email.html", success_url='/account/password-reset-done/'), name='password_reset'),
    # path('password-reset-done/', auth_views.PasswordResetDoneView.as_view(template_name="account/password_reset_done.html"), name='password_reset_done'),
    # path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="account/password_reset_confirm.html", success_url='/account/password-reset-complete/'), name="password_reset_confirm"),
    # path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='account/password_reset_complete.html'), name='password_reset_complete'),
    # path('my-information/', views.myself, name="my_information"),
    # path('edit-my-information/', views.myself_edit, name="edit_my_information"),
    # path('my-image/', views.my_image, name="my_image"),
]

djsite/blog/urls.py
from django.urls import path, re_path
from . import views

app_name= 'blog'
urlpatterns = [
    re_path(r'^$', views.blog_title, name='blog_title'),
    re_path(r'^(?P<article_id>\d)/$', views.blog_article, name='blog_detail')
]

djsite/djsite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('account/', include('account.urls')),
]

djsite/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}
    {% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
</head>
<body>
    {% include 'header.html' %}
    <div class="container">
        {% block content %}    
        {% endblock content %}
    </div>
    {% include 'footer.html' %}
    {% block javascript %}{% endblock %}
</body>
</html>

djsite/templates/footer.html
<div class='container'>
    <hr>
    <p class='text-center'>shenqichen</p>
</div>

djsite/templates/header.html
{% load staticfiles %}
<div class='container'>
    <nav class='navbar navbar-default' role='navigation'>
        <div class='navbar-header'>
            <a class='navbar-brand' href='http://www.itdiffer.com'>
                <img src="{% static '/images/logo.png' %}" width='100px'>
            </a>
        </div>
        <div>
            <ul class='nav navbar-nav' role='navigation'>
                <li><a href="{% url 'blog:blog_title' %}">BLOG</a></li>
            </ul>
            <ul class='nav navbar-nav navbar-right'>
                <li><a href="{% url 'account:user_login' %}">LOGIN</a></li>
            </ul>
        </div>
    </nav>
</div>